version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: fastapi_backend
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: streamlit_frontend
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "8501:8501"

networks:
  app-network: